spring.application.name=blogging-api

spring.datasource.url=jdbc:postgresql://localhost:5432/blogging_app
spring.datasource.username=ryu
spring.datasource.password=Ryu281007
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false